### PR TITLE
Fix multiple @apply involving responsive rules

### LINKED ISSUE #148: Wrong output order when using multiple @apply rules
### What version of @tailwindcss/jit are you using?

v0.1.7

### What version of Node.js are you using?

v.15.something

### What browser are you using?

Chrome

### What operating system are you using?

macOs

I noticed that the CSS output is in the wrong order if you use multiple `@apply` rules like this:

```
h1 {
  @apply text-2xl;
  @apply sm:text-3xl;
}
```

With this example the ` sm:text-3xl` rule is overwritten by `text-2xl`.

It does work as expected when I combine the rules in one `@apply` statement like this:

```
h1 {
  @apply text-2xl sm:text-3xl;
}
```

I wasn't sure if this is related to existing issues about @apply. If so, sorry for the duplicate issue 🙃.

### PR DESCRIPTION
**Pull request by thecrypticace**
Builds on #150 (so lets get that merged first and then I'll rebase this)

Closes #148

### CODE REVIEW

File: src/lib/expandApplyAtRules.js [hunk 1]
```diff
@@ -115,13 +122,24 @@ function expandApplyAtRules(context) {
...
+        }
+      }
+
+      for (const [parent, candidates] of perParentApplies) {
+        let siblings = []
+
+        for (let candidate of candidates) {
+          let applyCandidate = candidate[0]
+          let important = candidate[1]
+          let rules = candidate[2]
```
Comment (RobinMalfait) [inline src/lib/expandApplyAtRules.js:135]: Little nitpick, I think it might be cleaner if we write it as:

```suggestion
        for (let [applyCandidate, important, rules] of candidates) {
```

I double checked and as far as I can tell, we don't need the actual `candidate` so inlining it should be fine.

**Review by RobinMalfait — CHANGES_REQUESTED** [review]
Hey! Thank you for your PR!
Much appreciated! 🙏

Little nitpick, but apart from that, looks correct to me, thanks!

---

We'll wait for the other PR to be merged first (#150)

File: src/lib/expandApplyAtRules.js (hunk 1 above)
Comment (thecrypticace) [reply src/lib/expandApplyAtRules.js]: Yep, totally I was surgically moving stuff around and didn't think to collapse this. Good call!
